version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.dlsc.formsfx:formsfx-core
    versions:
    - ">= 10.a, < 11"
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - ">= 9.a, < 10"
  - dependency-name: org.jruby:jruby-complete
    versions:
    - "> 9.2.6.0"
  - dependency-name: org.asciidoctor:asciidoctorj
    versions:
    - 2.4.3
  - dependency-name: org.openjfx:javafx-web
    versions:
    - 15.0.1
    - "16"
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.1
    - 3.1.2
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - 11.0.3
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.0"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master-11
  ignore:
  - dependency-name: org.asciidoctor:asciidoctorj
    versions:
    - "> 1.6.2"
  - dependency-name: org.jruby:jruby-complete
    versions:
    - "> 9.2.6.0"
  - dependency-name: org.openjfx:javafx-web
    versions:
    - 15.0.1
    - "16"
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
    versions:
    - 3.1.2
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: org.controlsfx:controlsfx
    versions:
    - 11.0.3
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.0"
